class StaticVar(object):
    JUST_VPN_LOGIN_ERROR=601 #vpn账号出错
    JUST_ACCOUNT_LOGIN_ERROR = 602 #教务系统账号错误
    JUST_NO_EVALUATE=603 #未评价
    JUST_NO_SCORE=604# 没有成绩
    JUST_SPORT_ACCOUNT_ERROR=605 #体育学院密码错误
    JUST_LIB_SEARCH_ERROR=606#图书馆搜索错误
    JUST_APK_SELECT_ERROR=701#apk信息查询失败
    JUST_APK_FILE_TYPE_ERR=801#文件类型不符合要求
    JUST_APK_INFO_UPDATE_ERROR=802#apk信息更新错误
